### ISSUE TITLE
Modid is not lower case

### ISSUE THREAD

**Issue by DArkHekRoMaNT** [anegostudios/VSdotnetModTemplates#1]
The new template creates a mod with modid equal to the project name. It should be made lowercase and possibly cleared of unnecessary characters, otherwise it may cause problems for beginners

![image](https://github.com/anegostudios/VSdotnetModTemplates/assets/15899143/0c89b79c-5e1b-43f3-9775-5b995062a061)

![image](https://github.com/anegostudios/VSdotnetModTemplates/assets/15899143/88340bc8-7ada-42b7-93fb-2dbe5e274bc9)

**Comment by Th3Dilli** [comment]
yeah I noticed but I haven't found a good way to workaround that across all possible ways to use the template 

but at least the game does lowercase it on deserialization
https://github.com/anegostudios/vsapi/blob/master/Common/API/ModInfo.cs#L162

**Comment by DArkHekRoMaNT** [comment]
Add modid symbol in lowercase? 
```
"modid":{
      "type": "generated",
      "generator": "casing",
      "parameters": {
        "source":"_ProjectName_",
        "toLower": true
      }
    }
  }
```

**Comment by DArkHekRoMaNT** [comment]
Although the game changes the modid from modinfo, but assets/modid is still a problem for case sensitive filesystems

**Comment by Th3Dilli** [comment]
thank you, now I have added that :+1:
